### ISSUE TITLE
helvet and textcomp incompatibility in LaTeX2e 2020-02-02

### ISSUE THREAD

**Issue by tomh-overleaf** [latex3/latex2e#261] opened 2020-02-04 13:53 UTC
## Brief outline of the bug

Font encoding issues with `helvet` and the backtick char <code>`</code> in **TeX Live 2019** with **LaTeX2e <2020-02-02>**.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{helvet}
\usepackage{textcomp}

\begin{document}

\sffamily Backtick: ´

\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/4153704/test.log)

## Remarks

Some initial discussion is at https://chat.stackexchange.com/transcript/message/53437525#53437525

**Comment by u-fischer** [comment] 2020-02-04 13:58
Duplicate of #262

**Closed by u-fischer** 2020-02-04 13:58 UTC
