### ISSUE TITLE
Improve \ShowCommand

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#569] opened 2021-05-25 15:33 UTC
## Brief outline of the enhancement

The recently introduced command `\ShowCommand` should display the payload of commands declared with `\NewDocumentCommand` and friends.

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\newcommand\foo[1]{payload} \ShowCommand\foo
\renewcommand\foo[1][]{payload} \ShowCommand\foo
\RenewDocumentCommand\foo{o}{payload} \ShowCommand\foo
\RenewDocumentCommand\foo{m}{payload} \ShowCommand\foo

\stop
```

## Minimal example showing the desired new behaviour

Right now the payload is not shown for them but one just sees the argument scanning machinery and the fact that they are protected:
```
? 
> \foo=\protected macro:
->\__cmd_start:nNNnnn {o}\foo  \foo code {\__cmd_grab_D:w []}{}{}.
<argument> \foo 
                
l.6 ...entCommand\foo{o}{payload} \ShowCommand\foo
                                                  
? 
> \foo=\protected macro:
->\__cmd_start_expandable:nNNNNn {m}\foo  \foo  \foo code ?{\__cmd_expandable_g
rab_m:w }.
<argument> \foo 
                
l.7 ...entCommand\foo{m}{payload} \ShowCommand\foo
                                                  
? 
```

**Comment by blefloch** [comment] 2021-05-25 17:05
Duplicate of https://github.com/latex3/latex3/issues/795 on the LaTeX3 repository.  @PhelypeOleinik had more or less started, I beileve.

**Comment by FrankMittelbach** [comment] 2021-05-25 18:03
@blefloch  ah, didn't look there, because I consider this a 2e command :-) and I guess I like to track it here for inclusion into ltnews34 when written.

**Closed** 2021-09-22 17:50 UTC
Labels: enhancement, category base (latex), fixed in dev
