### ISSUE TITLE
bug in longtable (2024-04-26 v4.20) after a pagebreak

### ISSUE THREAD

**Issue by Reinhard-Jhr** [latex3/latex2e#1495] opened 2024-10-17 10:51 UTC
## After a pagebreak: \pagegoal=\maxdimen. 
\endlongtable -> .... \dimen@\pagegoal\advance\dimen@\ht\LT@foot\pagegoal\dimen@ ....

After a pagebreak you cannot add a positive value to \dimen@. This will lead to the error message: dimension too large.
I don't understand why you need this code, because the next command is an \endgroup and \pagegoal will be resetted. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

**Comment by davidcarlisle** [comment] 2024-10-17 16:04
Could you please supply a test file, the code shown in your description is empty

Setting the value just before `\endgroup` does look suspicous but not necessarily wrong it depends when the output routine is fired I'd need to check, and a test file would help...

This specific arrangement is relatively new (v4.14) from 819fda96d so your test file presumably doesn't show the issue if you use

```
\usepackage{longtable}[=v4.13]
```
?

**Comment by davidcarlisle** [comment] 2024-10-21 14:53
The group is not necessarily wrong (`\pagegoal` settings are global so survive the `\endgroup`)  However it is certainly true that  you can not increase pagegoal when it is `\maxdimen` so something is not right here. A test file would help, as noted above.

**Comment by Reinhard-Jhr** [comment] 2024-10-21 20:42
Excuse me, but the problem occurs in a very complex table. Here, longtable is only used indirectly in an environment that also allows page breaks within table cells and more. But in the end it is only longtable code. Unfortunately I was not able to create a simple example that shows the error. Therefore, I am sending an excerpt from the log file created with \tracingall, from which the problem can be seen.

[longtablebug.log](https://github.com/user-attachments/files/17466731/longtablebug.log)

version 4.13 does not show the error. \endlongtable is defined completely differently there.

**Comment by davidcarlisle** [comment] 2024-10-21 21:23
I can understand that making a minimal example is hard for this case. If you could send me privately the test file or put it in a private gh repository or whatever you find convenient, this would be really helpful This is a tricky area and making any change without a test file showing the problem is a bit stressful:-).

That said, it looks like line 255

```
    \dimen@\pagegoal\advance\dimen@\ht\LT@foot\pagegoal\dimen@
```

should look like  line 220

```
    \dimen@\pagegoal\advance\dimen@-\ht\LT@foot\pagegoal\dimen@
```

what happens if you add a `-` before `\ht` on line 225?

**Comment by Reinhard-Jhr** [comment] 2024-10-22 07:47
If you subtract \ht\LT@foot no error message appears, but the value of \pagegoal is senseless large. At the first moment the following code seems to make more sense:

\ifdim\pagegoal=\maxdimen%
 \pagegoal=\vsize\relax%
\fi%
\dimen@\pagegoal\advance\dimen@-\ht\LT@foot\pagegoal\dimen@%

But what value does \pagegoal get when the first box is entered in the current page? In addition, according to the TexBook, the value of \pagegoal cannot be changed, if it equals \maxdimen.

**Comment by davidcarlisle** [comment] 2024-10-22 08:50
> But what value does \pagegoal get when the first box is entered in the current page?

Try the following plain tex test, the value is `\maxdimen` even immediately after  `\pagegoal=5pt`

If you uncomment the `% x` then the 5pt is set and still visible after the group showing the global nature.

so 

```
\ifdim\pagegoal=\maxdimen%
\pagegoal=\vsize\relax%
\fi%
```

wouldn't have a lot of effect it would be `\maxdimen` again before it was used. The error here is that you can't set any length to more than `\maxdimen`

```

% x

\showthe\pagegoal

{\pagegoal=5pt
 \showthe\pagegoal

}

\showthe\pagegoal

\bye
```

**Comment by davidcarlisle** [comment] 2024-10-28 19:09
Yes as the PR is merged.

**Comment by FrankMittelbach** [comment] 2024-10-28 19:52
doesn't mean a thing ...sometimes ... could still be something open despite the merge ...anyway, good :-)

**Closed** 2024-10-31 18:21 UTC
Labels: category tools, fixed in dev
