### ISSUE TITLE
Make `\\` robust in all cases

### ISSUE THREAD

**Issue by eg9** [latex3/latex2e#203] opened 2019-10-28 10:16 UTC
## Brief outline of the bug

If `\raggedright` or similar declaration is in effect, then `\\` is no longer robust.

Adding `\MakeRobust\@centercr` solves the immediate issue in the following document.

Reference: https://tex.stackexchange.com/q/513912/4427

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\makeatletter
\protected@edef\test{a\\b}

\typeout{\meaning\test}

\raggedright

\protected@edef\test{a\\b}

\makeatother

\end{document}
```

## Log file (required) and possibly PDF file  
```latex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex 2019.10.18)  28 OCT 2019 11:14
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**crbug
(./crbug.tex
LaTeX2e <2019-10-01> patch level 1
(/usr/local/texlive/2019/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2019/10/15 v1.0g Bug-classification
) (/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2019/08/27 v1.4j Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (./crbug.aux)
\openout1 = `crbug.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
macro:->a\protect \\b
! Argument of \@firstoftwo has an extra }.
<inserted text> 
                \par 
l.13 \protected@edef\test{a\\
                             b}
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \@firstoftwo was complete.
<to be read again> 
                   \par 
l.13 \protected@edef\test{a\\
                             b}
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

! Missing \endcsname inserted.
<to be read again> 
                   \def 
l.13 \protected@edef\test{a\\
                             b}
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

! Illegal parameter number in definition of \test.
<to be read again> 
                   1
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   2
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   {
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   1
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   2
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   3
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   4
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   5
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   6
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   7
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   8
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   9
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   0
l.13 \protected@edef\test{a\\
                             b}
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Argument of \reserved@b has an extra }.
<inserted text> 
                \par 
l.13 \protected@edef\test{a\\
                             b}
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \reserved@b was complete.
<to be read again> 
                   \par 
l.13 \protected@edef\test{a\\
                             b}
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

! Missing \endcsname inserted.
<to be read again> 
                   \def 
l.13 \protected@edef\test{a\\b
                              }
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

! Illegal parameter number in definition of \test.
<to be read again> 
                   1
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   2
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   {
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   1
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   2
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   3
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   4
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   5
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   6
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   7
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   8
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   9
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

! Illegal parameter number in definition of \test.
<to be read again> 
                   0
l.13 \protected@edef\test{a\\b
                              }
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

(./crbug.aux) ) 
Here is how much of TeX's memory you used:
 722 strings out of 492167
 12588 string characters out of 6125388
 67956 words of memory out of 5000000
 5168 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 25i,1n,19p,142b,495s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
PDF statistics:
 0 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

**Comment by FrankMittelbach** [comment] 2019-11-02 12:16
This looks more complicated than I thought initially. `\MakeRobust` is not correct here I guess because it will add a `\protect` (aka `\relax`) and that will prevent the `\unskip` from seeing a previous space (could be fixed by using `\protected` I guess)

More importantly, the problem is more general as `\\`will also be fragile once it is set back to `\@normalcr`.

**Comment by FrankMittelbach** [comment] 2019-11-02 12:32
or not  :-)... I was mistaken in believing that \relax stops an \unskip

**Closed** 2020-01-31 18:37 UTC
Labels: bug, category base (latex), fixed in dev
