### ISSUE TITLE
ltxdoc: `\cs{\bslash}` and `\cs{\textbackslash}` no longer works properly

### ISSUE THREAD

**Issue by user227621** [latex3/latex2e#962] opened 2022-11-21 10:02 UTC
## Brief outline of the bug

When using the `ltxdoc` document class, `\cs{\bslash}` and `\cs{\textbackslash}` no longer works properly. You get "\\\\bslash" resp. "\\\\textbackslash". With previous versions of `ltxdoc`, you got "\\\\".  This issue shows up in the documentation of the `array` package: In section 1.1, "\\\\bslash" appears twice.

I don't know if this should be fixed in `ltxdoc` or in the documents using `\cs{\bslash}` or `\cs{\textbackslash}`. Note however that there are external documents which are affected by this issue: For example, I found "\\\\textbackslash" in the `ragged2e` documentation.

Furthermore, something like `\cs{begin\{document\}}` does not produce "\\begin{document}" anymore (also found in the `ragged2e` documentation), but I'm not sure if this is supported usage of `\cs`.

**Comment by muzimuzhi** [comment] 2022-11-21 17:05
Caused by PR #842 which (re)defines `\cs` to:
```tex
\DeclareRobustCommand\cs[1]{\texttt{\bslash\detokenize{#1}}}%
```
while in `doc.sty` `\cs` is defined as
```tex
\DeclareRobustCommand\cs[1]{\texttt{\bslash #1}}%
```

**Comment by FrankMittelbach** [comment] 2022-12-21 17:44
fixed in PL 1

**Closed by FrankMittelbach** 2022-12-21 17:44 UTC
Labels: bug, category base (latex)
