### ISSUE TITLE
\includegraphics does not set the box dimensions to the user asked-for width and height

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#112] opened 2019-01-14 18:27 UTC
## Brief outline of the bug

The actual width and height of the box may slightly differ. This can cause layout changes and even broken builds with third-party packages in some circumstances.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{graphicx}
\begin{document}
 

\sbox0{\includegraphics[width=100pt, height=455pt]{example-image-a}}

\ttfamily

requested height: \the\dimexpr 455pt\relax, \space\space\space\space
 (\number\dimexpr 455pt\relax sp)

obtained height : \the\ht0, (\number\ht0sp)

\end{document}
```

## Log file (required) and possibly PDF file  

[includegraphicsfeatureH.log](https://github.com/latex3/latex2e/files/2756514/includegraphicsfeatureH.log)

```
requested height:  455.0pt,     (29818880sp)
obtained height :  455.04608pt, (29821900sp)
```

Accordingly this is tiny difference (about one half of default `\vfuzz`).

It already means these two inputs behave differently:

```latex
\documentclass{article}
\usepackage{graphicx}
\usepackage[textheight=455pt]{geometry}
\begin{document}
 

\sbox0{A}\wd0=100pt \ht0=455pt
\box0

\end{document}
```

produces 1 page.

```latex
\documentclass{article}
\usepackage{graphicx}
\usepackage[textheight=455pt]{geometry}
\begin{document}
 

\sbox0{\includegraphics[width=100pt, height=455pt]{example-image-a}}
\box0

\end{document}
```

produces 2 pages.

And as reported at [tex.sx](https://tex.stackexchange.com/questions/469741/broken-build-if-a-too-big-picture-is-included-in-a-framed-environment-how-to-in) inclusion of a tall graphics in a `framed` environment (third party package) can cause broken build if it is close to `\textheight`. I have not examined it closely but I suspect a `1sp` is enough to trigger the neverending loop of `framed`.

**edit** certainly a 1sp triggers it (even if there is some weird range where one may be on or off, and not a sharp limit) but to be honest, as I don't know exactly which value near `\textheight-2\fboxsep-2\fboxrule - ???` puts `framed` into neverending loop, I use `\textheight-2\fboxsep-2\fboxrule - \baselineskip` which is at least a few points safe (about 7pt in my testing), so discrepancies of about `0.05pt` in dimensions do not matter at all. But I wanted to confer a dramatic aspect to my post. Hope I will be forgiven.

This issue is in same spirit as old report graphics/4451, but I have not read again in detail the discussion over there.

**Comment by davidcarlisle** [comment] 2019-01-14 19:30
Thanks for the report, accuracy of arithmetic is something we are looking at currently for other reasons

https://www.texdev.net/2018/12/09/floating-point-calculations-in-latex

as discussed in gnats 4451, the fact that you get the calculated not requested width was by design, most back ends then (and probably now) only really support scaling of an image so a user specification of 
`width=100pt`

 is implemented essentially as

`scale=(100pt/natural-width)`

 which means that there may be rounding error in the image size and at the time I thought it better to return the calculated size in all cases rather than special case the case where you just have width. you could have

`[width=1cm,rotate=45,scale=2,clip]`

 and the keyval package interface doesn't directly support answering the question

> "is the last key relevant to horizontal width the width key?"

We have discussed using the expl3 arithmetic instead of the dimen based arithmetic that graphics currently using, that would hide the problem in most cases due to the greater accuracy but I don't think it could guarantee never to be 1sp out even then.

perhaps we could add new keys `finalwidth=` and `finalheight=` which act like `width=` as far as scaling the graphic are concerned but which unconditionally also set the box width

`[finalwidth=100pt,scale=2]`

would then (presumably?) put an image of size 200pt in a box of width 100pt but in practice users just wouldn't do that...

I don't know, will think about it....

**Comment by jfbu** [comment] 2019-01-14 22:45
I think `finalwidth` and `finalheight` would considerably clarify user interface. Indeed, 

- `scale, width, height` or `width, scale, height`, or `width, height, scale` all three mean the same thing,

- `angle, width, height`, or `width, angle, height`, or `width, height, angle` mean three different things and it is needed to maintain for backwards compatibility but who really can "read" such specs and immediately form a mental picture of the result ? Plus, the first two will not give the exact same TeX height in sp units, due to different paths of computations. Further with a negative angle, rotating a rectangle creates depth, so one has to understand that the "height" is the TeX height, all of this is very complex and documentation very quick...

I did not test, but from the documentation I do not understand where is the point around which rotation is done when some viewport is specified: perhaps the bottom left point of original picture, perhaps bottom left point of viewport ? I know I am drifting off-topic, but I think the situation here is that backwards compatibility means maintaining features for which the documentation always remained extremely sparse so that as nobody complained this must mean that not all possible combinations of keys have been explored by user base, but only some basic ones.

For such user, and not modifying existing keys to keep backwards compatibility, `finalwidth` and `finalheight` would be very nice. As I have thought only 2seconds about it, it is my privilege to waive thinking about `finaldepth` and `finaltotalheight` and what makes sense. (After third second of reflexion, maybe only `finaltotalheight`).

And, now I don't think the matter is to change math engine. The precision achieved is typographically satisfying. Thus, I would simply forcefully set the final TeX dimensions to the one requested by user via `finalwidth` and `finalheight`. (that was my fourth second reflexion).

**Comment by davidcarlisle** [comment] 2019-01-14 23:02
> Thus, I would simply forcefully set the final TeX dimensions to the one requested by user via finalwidth and finalheight. (that was my fourth second reflexion).

The reason that I didn't do that originally I think was worrying about `\fbox{\includegraphics[...]{..}}` hopefully the size difference is small but if the image is bigger than the box dimension then you have to make it stick out of the box on one side or the other and so it may make the box margins look odd or in bad cases actually overprint the rules (if the image is set to overlap to the left or top). Hopefully the difference isn't visually noticeable and the reasons for needing exact dimensions are more to do with automated test comparisons but still ...

However if the behaviour is a user option with separate keys to force the final width then it is less of an issue, as it saves me having to decide which behaviour is best:-)

**Comment by FrankMittelbach** [comment] 2019-11-28 16:45
@davidcarlisle again one for the next release if you look at the keys of graphics anyway?

**Comment by davidcarlisle** [comment] 2020-02-06 12:55
Marking this as won't fix, as it may be addressed by merging with the l3 graphics back end.

**Closed by davidcarlisle** 2020-02-06 12:55 UTC
Labels: category graphics, enhancement, long-term
