### ISSUE TITLE
add normalisation of legacy m prefixes in \usefont

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#453] opened 2020-12-10 10:31 UTC
## Brief outline of the bug

Unlike other related commands `\usefont` does not automatically normalize legacy use of `m` in font series specifications (mapping mc to c for example)

This affects some existing packages as discussed on texhax

https://tug.org/pipermail/texhax/2020-December/024742.html

## Minimal example showing the bug

```latex
% contributed package needed here \RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{report}

\usepackage{ean13isbn}

\begin{document}
\EANisbn[ISBN=978-80-7340-097-2]
\end{document}
```

The intended condensed font is not used, so there is no error but the resulting output has overlapping characters.

Suggestion from @FrankMittelbach  is to re-use the `m` normalisation function used elsewhere

```
\DeclareRobustCommand\usefont[4]{\fontencoding{#1}%
    \edef\f@family{#2}%
    \edef\f@series{#3}%
    \series@maybe@drop@one@m\f@series\f@series   % <---
    \edef\f@shape{#4}\selectfont
    \ignorespaces}
```

**Comment by user227621** [comment] 2020-12-11 15:24
Maybe I'm completely wrong, but is `\series@maybe@drop@one@m\f@series\f@series` causing an infinite loop? The compilation of the following MWE does not terminate:
```
\documentclass{article}

\makeatletter
\DeclareRobustCommand\usefont[4]{\fontencoding{#1}%
    \edef\f@family{#2}%
    \edef\f@series{#3}%
    \series@maybe@drop@one@m\f@series\f@series   % <---
    \edef\f@shape{#4}\selectfont
    \ignorespaces}
\makeatother

\begin{document}

\usefont{OT1}{cmr}{m}{n} Lorem ipsum

\end{document}
```

Maybe the following is better?

```
\DeclareRobustCommand\usefont[4]{\fontencoding{#1}%
    \edef\f@family{#2}%
    \set@target@series{#3}%
    \edef\f@shape{#4}\selectfont
    \ignorespaces}
```

**Comment by FrankMittelbach** [comment] 2020-12-11 16:43
I relaized this morning that one can shorten the definition using `\set@target@series` (at the cost being minimally slower) but its definition is
```
\def\set@target@series#1{%
    \edef\f@series{#1}%
    \series@maybe@drop@one@m\f@series\f@series
}
```
which is exactly the same as the long form so no idea why one should loop and the other not in your case. It works here.

**Comment by user227621** [comment] 2020-12-11 17:06
Sorry. I compiled with LaTeX 2020-02-02 by mistake (I had previously done experiments for #444). The definiton of `\series@maybe@drop@one@m` was changed in LaTeX 2020-10-01. The definiton of `\series@maybe@drop@one@m` was changed in LaTeX 2020-10-01.

**Comment by FrankMittelbach** [comment] 2020-12-11 18:01
Ah But that's a good point. Because it means that my rollback is probably wrong.￼

**Comment by user227621** [comment] 2020-12-15 14:27
I have noticed two problems related to this issue. (I don't know whether these are bugs or whether this is by design.)

- `\fontseriesforce{...}` does not drop a legacy `m`. For example `\fontfamily{NotoSans-TLF}\fontseriesforce{mc}\selectfont` gives a warning and NotoSans-TLF/m/n is substituted instead of NotoSans-TLF/c/n. This could be fixed by using `\set@target@series{#1}` instead of `\edef\f@series{#1}` inside `\fontseriesforce`. (And probably delay this as proposed in #444.)
- `\usefont` does not set `\@forced@seriestrue`. Therefore, issues similar to [this situation](https://github.com/latex3/latex2e/issues/277#issuecomment-586619993) in #277 can arise:
```
%\RequirePackage[2019/10/01]{latexrelease}%uncomment to see the expected behaviour
\documentclass{article}

\begin{document}

\usefont{OT1}{NotoSans-TLF}{b}{n} Lorem ipsum \rmfamily Lorem ipsum

\end{document}
```
I would expect the second "Lorem ipsum" to be cmr/b/n, but I get cmr/bx/n. This could be fixed by adding `\@forced@seriestrue` to `\usefont`.

**Comment by FrankMittelbach** [comment] 2020-12-15 14:38
Am 15.12.20 um 15:27 schrieb user227621:
> I have noticed two problems related to this issue. (I don't know whether 
> these are bugs or whether this is by design.)
> 
>   * |\fontseriesforce{...}| does not drop a legacy |m|. For example
>     |\fontfamily{NotoSans-TLF}\fontseriesforce{mc}\selectfont| gives a
>     warning and NotoSans-TLF/m/n is substituted instead of
>     NotoSans-TLF/c/n. This could be fixed by using
>     |\set@target@series{#1}| instead of |\edef\f@series{#1}| inside
>     |\fontseriesforce|. (And probably delay this as proposed in #444
>     <https://github.com/latex3/latex2e/issues/444>.)

that's by design. Force should give you the ability to get what you ask 
for even if it is something that is normally adjusted.

>   * |\usefont| does not set |\@forced@seriestrue|. Therefore, issues
>     similar to this situation
>     <https://github.com/latex3/latex2e/issues/277#issuecomment-586619993> in
>     #277 <https://github.com/latex3/latex2e/issues/277> can arise:

that is not so clear  what the design should be here  -- have to think 
about it a bit further. But perhaps \usefont should behave like a forced 
setting.

**Comment by FrankMittelbach** [comment] 2020-12-16 16:20
>     * `\usefont` does not set `\@forced@seriestrue`. Therefore, issues similar to [this situation](https://github.com/latex3/latex2e/issues/277#issuecomment-586619993) in #277 can arise:
> 
> 
> ```
> %\RequirePackage[2019/10/01]{latexrelease}%uncomment to see the expected behaviour
> \documentclass{article}
> 
> \begin{document}
> 
> \usefont{OT1}{NotoSans-TLF}{b}{n} Lorem ipsum \rmfamily Lorem ipsum
> 
> \end{document}
> ```
> 
> I would expect the second "Lorem ipsum" to be cmr/b/n, but I get cmr/bx/n. This could be fixed by adding `\@forced@seriestrue` to `\usefont`.

I would say this is also by design and yes it is a change between LaTeX not supporting additional axes in series and not managing the series weight per meta family and now.

You use `\rmfamily`which switches to the roman "meta" family and doing so it determines if it is in a "bold context" and if so switches to the bold for the "rm" and that is for CMR "bx".  So, yes it is a border case but on the whole I think the meta family handling shold win unless you explicty say you want to see the series forced. `\usefont` was and is meant as a short way of using a specific font no more no less. And that should not stop one of themeta families to say what they mean by "bold".

**Comment by user227621** [comment] 2020-12-16 20:19
> You use `\rmfamily`which switches to the roman "meta" family and doing so it determines if it is in a "bold context" and if so switches to the bold for the "rm" and that is for CMR "bx". So, yes it is a border case but on the whole I think the meta family handling shold win unless you explicty say you want to see the series forced. `\usefont` was and is meant as a short way of using a specific font no more no less. And that should not stop one of themeta families to say what they mean by "bold".

@FrankMittelbach This explanation is understandable. Thanks for the clarification.

**Comment by FrankMittelbach** [comment] 2021-01-02 23:08
part of PL3

**Closed by FrankMittelbach** 2021-01-02 23:08 UTC
Labels: bug, category base (latex), fixed in hotfix
