### ISSUE TITLE
amsmath/hyperref: unary minus becomes binary at the begin of an equation

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#652] opened 2021-08-24 08:57 UTC
## Brief outline of the bug
If hyperref is used with amsmath, an unary minus becomes a binary minus as the `refstepcounter` inserts a destination. The suggested fix is to insert an empty mathopen after the `\refstepcounter`. 

References: 
https://tex.stackexchange.com/q/235665/2388
https://tex.stackexchange.com/q/610904/2388

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} %errors because of hyperref
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\begin{document}
\begin{equation}
  -1 = -1 
\end{equation}

\makeatletter
\def\incr@eqnum{\refstepcounter{equation}\ifmmode\mathopen{}\fi\let\incr@eqnum\@empty}
\makeatother

\begin{equation}
  -1 = -1
\end{equation}
\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/130588125-9323f3fd-f75d-4179-98e2-d27e1aa14c19.png)

## Log file (required) and possibly PDF file  

[b-467.log](https://github.com/latex3/latex2e/files/7037891/b-467.log)

**Comment by FrankMittelbach** [comment] 2021-08-24 09:55
I'm not convinced this is the right approach. The reason why there is an issue with hyperref is that hyperref changes the definition of `\equation` and moves `\incr@eqnum` into the math part. When doing that it could at the same time add the open atom as well. Then the test for math etc isn't unnecessarily done in all the places where `\incr@eqnum` is used outside math.

If there are changes to amsmath I think it should remove the patching need for hyperref not support and "incomplete" patch.

Anyway the suggest push in #653 is incomplete as it misses out resetting the definition in `\@arrayparboxrestore`. But as I said I think it is better to alter `\equation`to explicitly add the open atom after `\incr@eqnum` because then you don't need to test for math (you know you are in math) and it is only where it is needed.

**Comment by u-fischer** [comment] 2021-08-24 10:24
Well I would love to move the whole hyperref patch to amsmath. Would this here be ok?

~~~~
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\begin{document}
\begin{equation}
  -1 = -1
\end{equation}

\makeatletter
\if@fleqn
\else
\long\def\equation{%
        \mathdisplay@push
        \st@rredfalse \global\@eqnswtrue
        \mathdisplay{equation}%
        \incr@eqnum\mathopen{}%moved incr@eqnum + mathopen
      }%
\fi
\makeatother

\begin{equation}
  -1 = -1
\end{equation}
\end{document}
~~~~

(it will change  few testfiles imho)

**Comment by FrankMittelbach** [comment] 2021-08-24 10:40
what is the point of the fleqn exception? I don't think there should be one (even if that may have been the case in hyperref in the past).

Test files would change if we have showoutput on math equations but the change would be predictable and easy to verify (but it should be the same if your original suggestion would have been implemented and that didn't alter change files (so basically that part of the code is not tested (?)

**Comment by u-fischer** [comment] 2021-08-24 11:57
I can try what happens if one leaves out the fleqn exception. My original suggestion didn't change the test files as the mathopen would only have an effect if hyperref is loaded (which moves the incr@eqnum) and the test files don't cover this.

**Comment by u-fischer** [comment] 2021-08-24 12:58
The fleqn exception is needed: labels break if one move the equation number there too as fleqn has additional grouping:

~~~~
\documentclass{article}
\usepackage[fleqn]{amsmath}
\begin{document}
\begin{equation}
  -1 = -1
\end{equation}

\makeatletter
\if@fleqn
\else
\long\def\equation{%
        \mathdisplay@push
        \st@rredfalse \global\@eqnswtrue
        \mathdisplay{equation}%
        \incr@eqnum\mathopen{}%
      }%
\fi
\makeatother

\begin{equation}\label{a}
  -1 = -1
\end{equation}

\makeatletter
\long\def\equation{%
        \mathdisplay@push
        \st@rredfalse \global\@eqnswtrue
        \mathdisplay{equation}%
        \incr@eqnum\mathopen{}%
      }%
\makeatother

\begin{equation}\label{b}
  -1 = -1
\end{equation}

a:\ref{a}, b:\ref{b}
\end{document}
~~~~

gives 
![image](https://user-images.githubusercontent.com/4047173/130615952-53d28d3b-43b9-420d-813b-4e4cefb411a1.png)

**Comment by FrankMittelbach** [comment] 2021-08-24 13:03
As to no effect on the tests you are of course right :-) and the fleqn reimpl in amsmath looks like being more complicated than I thought. The way it is implemented the equation is actually split into the main formula (one `$...$`)  and the equation tag (separate formula) so moving the `\incr@eqnum` always inside the first means you loose the state of `\@currentlabel` before the tag is set ending in empty references.  So it has to be done differently as suggested.

**Comment by blefloch** [comment] 2021-08-24 17:01
This affects spacing, won't the ams people complain?  Should we do the same as
for the "aligned" environment where we ended up with longish option names for
various choices?

**Comment by FrankMittelbach** [comment] 2021-08-24 20:39
It doesn't affect spacing except in the case of an unary  (minus) at the start of the equation together with hyperref, in which case the current output is clearly wrong and it doesn't really matter if the fix is put into hyperref or into amsmath. More importantly if somebody had already fixed it in their source then the change will not alter that. Finally it doesn't affect paginiation.

**Comment by blefloch** [comment] 2021-08-24 20:53
> More importantly if somebody had already fixed it in their source then
> the change will not alter that.

Ok, I think you're right.  I was worrying about fixes like -\!1, but that wasn't
a fix anyways, so probably a less likely user choice compared to {-}1 or {-1}.

**Comment by car222222** [comment] 2021-08-25 08:37
This problem raises some general questions; these likely need a separate issue but I shall summarise here.
﻿
Whilst something non-optimal is of course needed now as a temporary fix for this case (in the combination of hyperref and amsmath), in general, it can always be dangerous to  add whatsits in such (random) places within the text (and even more so in mathmode).

The rules are that each whatsit (and similar nodes) should always be rigidly attached to something box-like that would be there anyways, without the whatsit node.  But in mathmode  this is insufficiently cautionary and so therein it is safest not to place them at all!   Far better to find somewhere outside the mathmode for all such nodes).

In general, adding further (spurious) nodes (such as an empty `\mathopen`) to the math list to ‘fix the spacing’ is equally unwise since it may have unwanted effects and is not really part of the intended maths.

**Comment by car222222** [comment] 2021-08-25 08:37
But also, maybe a more robust fix could be provided now?

Thus: to fix this and similar cases, it would be wise right now to investigate how never to add \refstepcounter and friends to math lists.

**Comment by davidcarlisle** [comment] 2021-08-25 09:01
On Wed, 25 Aug 2021 at 09:37, Chris Rowley ***@***.***> wrote:

> But also, maybe a more robust fix could be provided now?
>

In what way is adding a mathopen at the start not robust? the spacing after
a mathopen is the same as the spacing at  the start of a list..

Thus: to fix this and similar cases, it would be wise right now to
> investigate how never to add \refstepcounter and friends to math lists.
>

You could do this but it would most likely mean never using display math
and always, like align, constructing the display by hand.  Possible of
course but almost certainly incompatible with something since equation has
been a thin wrapper around $$ forever.

**Comment by u-fischer** [comment] 2021-08-25 09:17
> Whilst something non-optimal is of course needed now as a temporary fix for this case (in the combination of hyperref and amsmath), in general, it can always be dangerous to add whatsits in such (random) places within the text (and even more so in mathmode).

Well it is not really a temporary fix as it does what could have been done directly if at the time amsmath has been written they would have known about links and destinations: It places the refstepcounter in a place where it doesn't harm that it does more than increasing a number but also contains a whatsits.

Why do you think the place is sub-optimal? Do you have an example where it harms there?

**Comment by car222222** [comment] 2021-08-25 09:50
@davidcarlisle "In what way is adding a mathopen at the start not robust?"

I am not saying that this particular fix for this case is itself not robust.  If this (and a mathclose for the end) are to be standard practice then this should be documented, with an explanation of why it is "always robust", when it is needed and of any precautions that need to be taken in a using it.

"the spacing after is mathopen is the same as the spacing at the start of a list"   Good, so document when it is a good idea to use this to get the spacing right.

But there are more dangers in adding whatsits to mathlists; it is just not getting unexpected spacing.  

And anyway, adding spurious math structure just to get it to look right sounds dodgy to me in these days of "preserving the document structure".

But whatever is robust and a Good Thing should indeed be fully supported, with good documentation.

**Comment by car222222** [comment] 2021-08-25 09:57
@u-fischer  If LaTeX was (or will be) intended to work well with hyperref-type stuff then better ways are needed to deal whatsits, especially around/within maths.  
Simply grafting on Heiko-inspired patches will not "cut the mustard" in most cases.  

Anyway, the longevity of supporting whatsits in mathmode is something the future will determine.

**Comment by josephwright** [comment] 2021-08-25 10:07
@car222222  See https://github.com/lvjr/tabularray/: I think that's done without `\halign` (I've not dug through the detail, but I know that it's not a simple `tabular` approach.)

**Comment by zauguin** [comment] 2021-08-25 10:26
> But there are more dangers in adding whatsits to mathlists; it is just not getting unexpected spacing.

The problem here is specifically not adding the whatsit to the mathlist, the problem is adding a hbox containing a whatsit to the mathlist. The whatsit by itself wouldn't influence spacing at all.

> And anyway, adding spurious math structure just to get it to look right sounds dodgy to me in these days of "preserving the document structure".

When looking at this from the point of view of preserving the document structure, then placing the target corresponding to the math list as part of the math list seems more correct then jumping outside of the math list whenever the math list is linked.

**Comment by car222222** [comment] 2021-08-25 10:34
"The whatsit by itself wouldn't influence spacing at all."

Aha!  Good, there is hope for whatsits then.  I had not noticed that there was a box causing the problem: oops! 

"When looking at this from the point of view of preserving the document structure, then placing the target corresponding to the math list as part of the math list seems more correct then jumping outside of the math list whenever the math list is linked."

Agreed, but even without the math, in PDF structure and links etc do not mix well.

**Comment by car222222** [comment] 2021-09-05 09:26
May I make s bold as to suggest that this fix should be given a layer of indirection?
I cannot think of a very good name for it right now, so I am going to call it \fix@spacing here.

This command, \fix@spacing, would expand primarily to \mathopen{} (as in the current temporary fix) but would allow alternative expansions, in case of need, by other packages and systems.  For example, this would support easily treating it as a null operation, for systems such as tex4ht(?) that do not need to fix the spacing and do not want to have to determine whether the \mathopen is ‘real’ or not.

**Comment by car222222** [comment] 2021-09-07 02:49
Maybe not yet finally fixed?

**Closed** 2021-09-22 17:52 UTC
Labels: bug, category amsmath, fixed in dev

**Comment by lstonys** [comment] 2024-06-25 10:34
` \mathopen{}` in tex4ht changes next atom class and the first character now turns into `MathClass-open`.
From your example  `-1 = -1`  we get 
```
<mo class='MathClass-open' stretchy='false'><mfont mathvariant='normal'>−</mfont></mo><mn>1</mn> 
<mo class='MathClass-rel' stretchy='false'>=</mo> 
<mo class='MathClass-bin' stretchy='false'><mfont mathvariant='normal'>−</mfont></mo><mn>1</mn>
```
Would be better to add ` \mathopen{}` via `\fix@spacing` where in thex4ht it could be set to `\empty`.
