### ISSUE TITLE
Page breaks allowed between \section and \subsection

### ISSUE THREAD

**Issue by dpthurst** [latex3/latex2e#81] opened 2018-10-03 01:20 UTC
## Brief outline of the bug
In the amsart style, page breaks are frequently allowed after a \section heading immediately followed by a \subsection, if the \subsection has a label. In the attached example, if the \label command is deleted, then the Section and Subsection heading are properly kept on the same page.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{amsart}

\begin{document}
\section{Intro}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ornare scelerisque aliquet. Curabitur dictum venenatis leo eu efficitur. Sed at consectetur turpis. Praesent rhoncus eu tellus eu mollis. Sed nec tortor nec magna auctor placerat nec quis ante. Sed lectus ipsum, lobortis vel erat ac, consequat convallis turpis. In at massa sed justo hendrerit porta. Sed ornare ipsum a ligula euismod egestas. In eget congue eros. Aenean elementum mi a dapibus tristique. Nullam faucibus sagittis ligula, quis fringilla massa dapibus ac. Aliquam non justo non odio tincidunt commodo at et mi. Nulla at eleifend massa.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque mollis ultrices massa, id blandit ante euismod at. Mauris non leo at turpis suscipit laoreet sit amet vitae ex. Praesent et elementum risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean nisl orci, mattis et finibus sed, efficitur non nisl. In tortor arcu, scelerisque ac sapien posuere, maximus mollis magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris rutrum feugiat hendrerit. Praesent finibus eu quam id rhoncus. In semper metus sed nisi rutrum finibus.

Vestibulum pretium interdum ex ornare malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean porta lobortis pretium. Quisque sed egestas mi, eu auctor enim. Proin vestibulum ipsum vel scelerisque porttitor. Donec lorem erat, volutpat rutrum dui vitae, molestie euismod velit. Duis convallis metus vel sem gravida, molestie iaculis tellus mollis. Mauris varius commodo ligula a volutpat. Morbi quis rhoncus ante. Suspendisse pulvinar tortor egestas, placerat lacus sed, ultricies sapien. In luctus pharetra eros, ac lacinia est. Cras varius eget ligula eget vulputate. Sed ac malesuada metus, tincidunt faucibus odio. Nam tincidunt ultricies ultrices.

In luctus lorem lorem, a rhoncus ipsum elementum eu. Vivamus eu imperdiet urna. Integer id bibendum risus, semper rhoncus ante. Sed semper, lectus eu consectetur lacinia, sapien purus consequat arcu, vel congue ex purus et purus. Sed eu mauris sapien. Aliquam in urna sed nisi mattis semper. Fusce vel eros faucibus justo placerat ullamcorper sed sed arcu. Morbi consectetur feugiat efficitur. In quis aliquet nisi. Ut condimentum varius vestibulum.

Proin cursus interdum gravida. Nulla tristique libero vel euismod interdum. Donec egestas vel mauris non tincidunt. Fusce finibus dapibus orci vitae faucibus. Nullam lorem nibh, placerat ac placerat vel, consequat at turpis. Nunc dapibus vel nibh vitae tristique. Praesent finibus at urna et gravida. Duis hendrerit metus eget nibh pharetra sollicitudin.

Morbi eu scelerisque dui. Cras dictum eleifend ultrices. Quisque
aliquet est in auctor ultrices. Cras finibus vulputate libero eu
vulputate. Sed sed commodo turpis. Donec varius mi purus, a fermentum
velit mattis malesuada. Sed facilisis convallis tortor et blandit. Sed
auctor sed felis vitae condimentum. Mauris tristique eleifend orci,
sed sollicitudin odio tincidunt in. Nulla luctus blandit auctor. Donec
pellentesque tortor at massa suscipit ornare. Morbi non urna in lorem
blandit iaculis at sit amet quam. Sed auctor sed felis vitae condimentum. Mauris tristique eleifend orci, sed sollicitudin odio tincidunt in.

\section{Test}
\subsection{Subsec}\label{subsec}
Aenean dignissim viverra porttitor. Quisque eu ex et sem posuere tincidunt ut ut nulla. Suspendisse ornare neque non massa auctor, vel vulputate purus rutrum. Nam non sagittis tortor. In malesuada dui eget consectetur venenatis. Integer tempor libero in semper suscipit. Proin blandit dignissim lectus ut aliquam. Curabitur id sem malesuada, venenatis felis non, dictum justo. Suspendisse rutrum eros at velit placerat, porta finibus tortor posuere. Proin a justo finibus, laoreet velit vitae, dictum arcu.

In non dolor ex. Aliquam quis enim at nisl elementum pellentesque. Etiam purus sapien, ornare vel vestibulum congue, sollicitudin sed ex. Morbi a nisi eu risus fringilla pretium. Ut sollicitudin, risus eu feugiat eleifend, ex ex lobortis risus, condimentum efficitur dolor metus dapibus urna. Suspendisse quis pretium sem, id venenatis tellus. Nulla ultricies accumsan convallis. Fusce gravida consequat metus.
\end{document}
```

## Log file (required) and possibly PDF file  
[t.log](https://github.com/latex3/latex2e/files/2440230/t.log)
[t.pdf](https://github.com/latex3/latex2e/files/2440231/t.pdf)

**Comment by davidcarlisle** [comment] 2018-10-03 08:14
This is actually not dependent on amsart 

```

\RequirePackage{latexbug}
\documentclass{article}

\begin{document}
\section{Intro}

aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa

aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa

aa\\aa\\aa\\aa\\aa\\aa\\aa\\aa\\aa\\aa\\aa

aaa\\aaa

\subsubsection{Test}
\paragraph{Subsec}\label{subsec}
zz\\zz
\end{document}
```

The problem is `\label` and you get the intended layout if you place the label in a safer place

   `\subsection{Subsec\label{subsec}}`

I'm not sure if the code here can be made more robust in a compatible way, but we can look at it, thanks for the report.

**Comment by FrankMittelbach** [comment] 2018-10-03 10:52
@dbitouze it is the documented syntax by Leslie Lamport and for that reason the toc macros render `\label` and `\index` harmless when writing out to the toc file. It it, however, a syntax that I don't like personally. So we should see if we can make `\label` issue a `\nobreak` if encountered in vertical mode with the `@nobreak`switch turned on.

**Comment by FrankMittelbach** [comment] 2018-10-25 12:49
guess that is fixed now

**Closed** 2018-10-25 12:49 UTC
Labels: category base (latex), enhancement, works as designed
