### ISSUE TITLE
New hook management breaks ordering guarantee

### ISSUE THREAD

**Issue by hmenke** [latex3/latex2e#441] opened 2020-11-27 18:20 UTC
## Brief outline of the bug

Previously all the code that was placed in `\AtBeginDocument` was ordered by insertion.  Now each package gets its own scope which leads to reordering, breaking old documents which rely on this behavior.  In particular this breaks documents like this:
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\usepackage{unicode-math}
\AtBeginDocument{\renewcommand\vec{\mathbfit}}
\begin{document}
\meaning\vec% wat?
\end{document}
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

% inserted into top-level
\AtBeginDocument{\newcommand\foo{something unrelated}}

% orders nested after top-level
\makeatletter
{
    \renewcommand\@currname{nested}
    \AtBeginDocument{\renewcommand\foo{nested}}
}
\makeatother

% appends to top-level and therefore ordered before unicode-math, very unexpected!
\AtBeginDocument{\renewcommand\foo{top-level}}

\begin{document}

\meaning\foo% wat?

\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/5609217/test.log)

**Comment by davidcarlisle** [comment] 2020-11-27 19:05
You could specify  new label, but perhaps `unicode-math` should arrange that its insertions happen before  any atbegindocument in the preamble, by including the ordering rules shown in the preamble here.

```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\usepackage{unicode-math}
\DeclareHookRule{begindocument}{unicode-math-luatex}{before}{top-level}
\DeclareHookRule{begindocument}{unicode-math-xetex}{before}{top-level}

\AtBeginDocument{\renewcommand\vec{\mathbfit}}

\begin{document}
\typeout{^^J::: \meaning\vec}% wat?
\end{document}
```

**Comment by hmenke** [comment] 2020-11-27 19:14
Such ordering declaration will the be necessary for *every* package that uses `\AtBeginDocument` then.

**Comment by davidcarlisle** [comment] 2020-11-27 19:15
@hmenke  no its a judgement the package author can make. (A different choice for unicode-math that actually might be better for other reasons is for it not to delay its definitions.

**Comment by hmenke** [comment] 2020-11-28 15:18
I don't think this is sufficient, because every construction like
```
\AtBeginDocument{<whatever>}
\usepackage{<package that uses \AtBeginDocument>}
\AtBeginDocument{<override something from that package>}
```
is now broken.

**Comment by FrankMittelbach** [comment] 2020-11-28 22:17
> Previously all the code that was placed in `\AtBeginDocument` was ordered by insertion. Now each package gets its own scope which leads to reordering, breaking old documents which rely on this behavior. In particular this breaks documents like this:

Henri

It is true that the introduction of the hook management has broken this document but this was not by design but an oversight at our end. We didn't realize that

    \usetikzlibrary{external}

behaves currently as if it is part of the user preamble code while in fact it is more like a `\usepackage` mechanism. As a consequence something like `\AtBeginDocument` inside, currently appears as if is in the top-level scope done by the user (even though he or she have never issued it) and not as it should be in its own scope called `tikz-external' or similar.

That current behavior is not by design and needs correcting as that `\AtBeginDocument`is hidden to the user and therefore the behavior is truly surprising and unwanted.

---------

However what is by design is that each package gets its own scope and as a consequence the "preamble" gets its own scope as well.
 One of the reasons for this change is to make hook code manageable and resolve (over time) the big issues many users have that packages need to be loaded in specific (sometimes contradicting) order, because the code ending in hooks like "begindocument" was unmanaged and package writers had, as their only option the possibility to try testing for all kind of dependencies and ask the user for specific orders or even trying to patch the code already placed in "begindocument".

As I said, due to this change the preamble has also its own scope called `top-level` and without any specific rules this means that several `\AtBeginDocument` calls in the preamble will be inserted in the hook at the point where the first happens. This is a change but when we discussed the implications of a standardized design we thought (and still think) that the change is warranted. One one hand there are very few documents that use `\AtBeginDocument` several times in different places in the preamble and if they do *and* that causes a problem then this problem can be easily resolved by moving all `\AtBeginDocument` calls to the end of the preamble.

And two months into general distribution of the new format seem to validate that opinion: yours its the first report that something is not working as expected and it is not due to several `\AtBeginDocument`s in the preamble, but due to the unfortunate side-effect that `\usetikzlibrary` to the mechanism appears as if it is user code.

As I said that was neither intended nor should it stay like that. In our opinion something like `\tikzlibrary` or `\tcbuselibrary` that offers a similar interface for loading "package-like" code should be able to introduce their own scope in order to participate in the rule management of the hook management of LaTeX. As we have overlooked this type of coding style, we have not provided a public interface for it, but that can be easily corrected as the mechanism for it are all in place.

So what what we like to do in order to resolve the problem is to provide

     \PushDefaultHookLabel{ <Label-name> }
     \PopDefaultHookLabel

in Patchlevel 3 coming out in the new few days and ask you to please adjust `\usetikzlibrary` so that for each library it loads it sets the Default Hook Label to the name of the library (perhaps prefixed by tikz- I would suggest) and pops the stack when it is done. This way the behavior is always identical whether loaded in the preamble or loaded inside some other package or class.

Inside such a library the library developer is then still able to change the label if so desired either by providing a different default or by using an explicit label on \AddToHook` or `\AtBeginDocument`.

To ensure backwards compatibility with older installations all that would be required is

\providecommand\PushDefaultHookLabel[1]{}
\providecommand\PopDefaultHookLabel{}

in tikz.sty in addition.

I hope that is acceptable as a solution to the problem while improving and standardizing the LaTeX interfaces.

**Comment by hmenke** [comment] 2020-11-28 22:26
That the problem surfaced with `\usetikzlibrary{external}` was just a coincidence.  In fact `\usetikzlibrary` should *not* participate in any “package-like” loading structure because the code should be entirely format-independent.  The fact that `external` violates this is a well-known problem and I've already pushed a quick fix for it: https://github.com/pgf-tikz/pgf/commit/a651531ea23409f0019efd9d49cfa72fe5ff216d

**Comment by SSegletes** [comment] 2020-11-30 16:55
I experienced a problem with the revised hook system from 2020-10-01.  After chat discussion on stackexchange, several folks chimed in to help address the issue, namely @PhelypeOleinik and @Skillmon.  The problem can be described as such:

I am loading `tocloft` inside a `cls` file to get some features, which redefines `\tableofcontents`. Using `\AtBeginDocument` in the `cls` (following the load of `tocloft`), I am now unable to patch with desired revision for `\tableofcontents. Same applies to \listoffigures and \listoftables.  Previously, this approach worked.

The solution offered, which also includes backward compatibility to prior tex engines is given below.  It involves creating a new hook, and ordering the hooks to load in the preferred order

    \providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
    \IfFormatAtLeastTF{2020-10-01}{\DeclareHookRule{begindocument}{./tocloft-patch}{after}{tocloft}%
      \AtBeginDocument[./tocloft-patch]}{\AtBeginDocument}{<my patched version of  \tableofcontents, etc.>}

**Comment by FrankMittelbach** [comment] 2020-12-01 16:22
### Update

I are planning to address the issue in a patch-level release for LaTeX (PL3). Might take us a few days for a number of reasons but probably within the next two weeks.

**Comment by hmenke** [comment] 2020-12-01 16:36
I have also made a PGF release today which works around the problem from `external` not having a proper package scope: https://github.com/pgf-tikz/pgf/commit/a651531ea23409f0019efd9d49cfa72fe5ff216d

All other uses of `\AtBeginDocument` in PGF should be unaffected by this bug, because they are somewhere in `pgfsys-*.def` which are loaded as part of `\usepackage{pgf}`.  Of course, if a user chooses to load it via `\input{pgf.sty}` all bets are off.

**Comment by RuixiZhang42** [comment] 2020-12-07 21:58
Is it possible to maintain an “internal hook rule” that respect the loading order of the packages? For example,
```latex
\usepackage{<packageA that uses \AtBeginDocument>}
\usepackage{<packageB that uses \AtBeginDocument>}
\usepackage{<packageC that uses \AtBeginDocument>}
```
Then internally, LaTeX can say the equivalent of
```latex
% internal hook rules
\DeclareHookRule{begindocument}{packageA}{before}{packageB}
\DeclareHookRule{begindocument}{packageB}{before}{packageC}
```
Now, if some packages or users give explicit rules, then these extra rules is appended to the internal rules:
```latex
% internal hook rules
\DeclareHookRule{begindocument}{packageA}{before}{packageB}
\DeclareHookRule{begindocument}{packageB}{before}{packageC}
% users hook rules
\DeclareHookRule{begindocument}{packageC}{before}{packageB}
...
```

**Comment by FrankMittelbach** [comment] 2020-12-07 22:30
The main reason for hook mangement is to get rid of arbitrary loading order influcening the resulting code, i.e., 
the design is that
 - code added by package A and package B to some hook is supposed to be independent so order is allowed to be arbitrary
 - if that assumption is not correct it can be specified in which order the code should be executed (that's what rules are for)

Introducing internal rules that bring enforce package ordering just brings us back to the issue LaTeX had in the past. In your example you end up with two confliction rules `B<C`  and `C<B` so either you have to issue an error: "unresolvable rules" or you have to invent secondary classes of rules which only apply if there aren't primary ones overwriting them. That would most certainly be extremely messy and not understandable in terms of what is going on.

The issue in the thread is rather special in that top-level, that is preamble usage is something where you do not expect as a user that your code is seemingly executed earlier than it is specified. Part of the problem was that  the tikzlibrary was pretending it is user code in the preamble ie not running in its own scope (as packages do)  but even without this the fact that with several `\AtBeginDocument` there is the surprise that everything is executed as if it has been specified in the first place not at the end.

Our conclusion after analysing the situation is that
 - something like tikzlibrary  or tcblibrary needs to behave like a package with respect to the hook management (and Henri already changed the library calling \AtBeginDocument with respect to that) though there may be one or two other cases with the tcolorbox libraries that also need to be resolved
 - and that we will change the behavior of "top-level" in general: top-level will always come last i.e., not participate in ordering because that is what the natural expectation would be. And if for some special reason you do want ordering of  `\AddToHook` calls made in the preamble then all you need to do it to give them a label.

**Comment by RuixiZhang42** [comment] 2020-12-07 22:41
@FrankMittelbach 
> top-level will always come last 

Fantastic news! This will also resolve many of the `\AtBeginDocument`’s that are added (a)&nbsp;directly in the preamble and (b)&nbsp;via `\input` (i.e., my several patches to commercial packages).

**Comment by FrankMittelbach** [comment] 2020-12-07 22:49
> Fantastic news! This will also resolve many of the `\AtBeginDocument`’s that are added (a) directly in the preamble and (b) via `\input` (i.e., my several patches to commercial packages).

that's the two use cases we want to cater for but without introducing a lot of complexity in the underlying concept. (it does even solve the library problem automatically, even though we that that such libraries should look like packages to the hook management (i.e., get their own scape and default label) so that they can be managed if necessary. 

It will take a few mor days to implement but that is what is planned for PL3

**Comment by FrankMittelbach** [comment] 2021-01-02 23:11
Part of PL3

**Closed by FrankMittelbach** 2021-01-02 23:11 UTC
Labels: category base (latex), fixed in hotfix
