### ISSUE TITLE
is \marks e-primitive now required?

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#846] opened 2022-06-10 01:08 UTC
Does the new release of LaTeX now require the \marks e-primitive, or some such? I'm guessing so, from what I read in the ltnews.

Prote/HiTeX doesn't have it, so hilatex fails to build. The error message is
```
! Undefined control sequence.
<recently read> \newmarks
l.16797 \NewMarkClass {2e-left}
```
not about \marks directly, which makes me wonder if some kind of fallback is implemented.

For now I've disabled hilatex.

DIdn't notice before now since I never enabled building hilatex-dev. Guess I should. Sigh.

**Comment by PhelypeOleinik** [comment] 2022-06-10 03:56
> Does the new release of LaTeX now require the \marks e-primitive, or some such?

It does.  More precisely, `\tex_marks:D` here:

https://github.com/latex3/latex2e/blob/d8791a6d2b0c67e884ca142048b8d93de72418b0/base/ltmarks.dtx#L1105

> Prote/HiTeX doesn't have it, so hilatex fails to build.

Hm...  I think they should have, since it's an e-TeX extension.  I contacted Thierry.

> not about \marks directly, which makes me wonder if some kind of fallback is implemented.

None, actually.  LaTeX assumed that if `\marks` was not there, `\newmarks` wouldn't be used.  Not the case anymore, so maybe this could be fixed.

**Comment by josephwright** [comment] 2022-06-10 06:39
We formally required e-TeX several years ago, so we don't test for specific primitives within that set. As @PhelypeOleinik  says, this is presumably an error in HiTeX.

**Comment by FrankMittelbach** [comment] 2022-06-10 07:47
> DIdn't notice before now since I never enabled building hilatex-dev. Guess I should. Sigh.

yes you should I would say: for all engines that implement the LaTeX format and are distributed by TL. Especially for engines that have implementations that deviate a lot from the core engines. 

But to the actual problem at hand: all eTeX extensions are required by LaTeX and we will make more and more use of them (after having formally stated for the last ten years or so that this is going to happen). And for none of these extensions fallbacks are feasible: you can make the error go aways easily enough, but that means that a part of LaTeX is then not functioning if used and going forward that would not help you much beyond being able to produce a crippled format without running into an error then.

The fact that we went kindly on ignoring `\newmarks` when not there is due to the fact that this code was written before we formally required eTeX (and was never taken out). Until now it didn't matter (or only for the few packages that used `\marks`) but now it is already the core code that wants to use both.

**Comment by aminophen** [comment] 2022-06-10 13:31
I remember HiTeX lacks \marks primitives by design, see hitexman.pdf section 2

**Comment by car222222** [comment] 2022-06-10 15:44
Whilst hitexman.pdf lists these as exceptions that have not been added, it gives no reason for this.  Thus it is unclear whether their omission is necessary.

**Comment by FrankMittelbach** [comment] 2022-06-10 22:32
As Martin said he understand that LaTeX doesn't need `\marks` and `\newmarks` so he didn't implement them (as he has no use for them in hitex), but that was a misunderstanding of what LaTeX requires and now the kernel (and not only some packages) need it. But the implementation should be trivially possible given that hitex supports `\mark` (by ignoring it (I presume)) and for `\marks` the same should happen with a simple twist, given that there is a number to parse.

**Comment by aminophen** [comment] 2022-06-10 22:59
Martin wrote to me privately on March 3rd

> The line breaking routine is running in the viewer and the HINT file format specifies all the parameters for the line breaking algorithm. So when I started in 2017, I tried to keep the project as small as possible to make shur I would be able to complete it.
> By now, the state of the project is far beyond of what I had expected then. But the HINT file format specification still covers just the line breaking of Don's original TeX. And therefore the viewer will also do just that, and hitex can not produce files doing more than that. Of course that might not be so for ever.
> Another design decission was to keep the TeX interpreter (and the TeX programming language) out of the HINT viewer. So there are no token lists in HINT files. This means no output routines and no marks, which I tried to replace be page templates, which is a largely untested aerea.
> The missing primitives are those that deal with line breaking, especially with right to left reading, and with marks.

**Comment by davidcarlisle** [comment] 2022-06-10 23:29
I may be enough to emulate `\marks` in `hilatex.ini` eg

```
\protected\def\marks{\begingroup\afterassignment\hitexfakemarks\count0=}
\def\hitexfakemarks#1{\endgroup}

\marks 5 {abc}
```

**Comment by FrankMittelbach** [comment] 2022-06-11 09:01
something like this, yes, but perhaps adding in `\mark{}` at the beginning, just to make sure that there is a "mark" in the stream in case some coding expects one (not likely, but who knows).

**Comment by FrankMittelbach** [comment] 2022-07-22 12:11
I think we can now call this resolved with hitex supporting \marks (in some form or shape)

**Closed by FrankMittelbach** 2022-07-22 12:11 UTC
