### ISSUE TITLE
Missing \ExplSyntaxOff in xparse-2020-10-01.sty

### ISSUE THREAD

**Issue by komascript** [latex3/latex2e#504] opened 2021-02-16 10:05 UTC
`xparse-2020-10-01.sty` has a `\ExplSyntaxOn` but no corresponding `\ExplSyntaxOff`. Because of this, with

```latex
\RequirePackage[2020/02/01]{latexrelease}
\documentclass{article}
\typeout{space catcode before loading xsparse=\the\catcode`\ }%
\RequirePackage{xparse}%
\typeout{space catcode after loading xparse=\the\catcode`\ }%
\begin{document}
Test
\end{document}
```

you get

```
space catcode before loading xsparse=10
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-2020-10-01.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.tex)))
space catcode after loading xparse=9
```

But with

```latex
\RequirePackage[2020/02/02]{latexrelease}
\documentclass{article}
\typeout{space catcode before loading xsparse=\the\catcode`\ }%
\RequirePackage{xparse}%
\typeout{space catcode after loading xparse=\the\catcode`\ }%
\begin{document}
Test
\end{document}
```

The result is as expected:

```
space catcode before loading xsparse=10
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-2020-10-01.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.tex)))
space catcode after loading xparse=10
```

**Comment by PhelypeOleinik** [comment] 2021-02-16 11:09
Hm, I transferred this issue because the bug is not in `xparse`: note the same files are loaded in both cases, and you get the same behaviour with any `expl3`-based package:
```latex
\begin{filecontents}{myexpl3pkg.sty}
\ProvidesExplPackage{test}{2020-20-20}{1.0}{Testing}
\end{filecontents}
%
\RequirePackage[2020/02/01]{latexrelease}
\documentclass{article}
\typeout{space catcode before loading myexpl3pkg=\the\catcode`\ }%
\RequirePackage{myexpl3pkg}
\typeout{space catcode after loading myexpl3pkg=\the\catcode`\ }%
\begin{document}
Test
\end{document}
```

The `\ExplSyntaxOn`/`Off` status is managed by `\@pushfilename` and `\@popfilename` in the same way as `\makeatletter`/`other`.  Prior to `2020-02-02` the `expl3` syntax management was patched by `expl3.sty` _into_ `\@push`/`\@popfilename`, and after the `expl3` integration it is there by default.  The problem is that rolling back removes that part of the code and the automatic `\ExplSyntaxOff` after the package ends is no longer there.

I think this is one scenario where rolling back shouldn't roll back all the way through.  We can either do a fake rollback and keep the `expl3` syntax management in place (after all rolling back doesn't remove `expl3`), or do a clever checking whether `expl3.sty` is loaded and if it isn't, undefine `\ProvidesExplPackage`, so that a package will need to load `expl3.sty` explicitly, thus apply the patch... I don't like the looks of the second option :)

**Closed** 2021-05-04 16:09 UTC
Labels: bug, category base (latex), fixed in dev
